version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py
  
formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/requirements.txt
formats:
  - htmlzip
